### ISSUE TITLE
Migrate CI

### ISSUE THREAD

**Issue by bmaupin** [bmaupin/react-civ5save#33]
~~The migration is already done, so it should just be a matter of updating README.md à la https://github.com/bmaupin/go-epub/commit/8dc2323be8d39b2322f4cc7a95adc90f69ce318a~~

**Comment by bmaupin** [comment]
Hmm, it seems Travis CI may no longer offer free builds for open-source projects: https://news.ycombinator.com/item?id=25338983

It might be better to migrate to GitHub Actions...

**Comment by bmaupin** [comment]
Try the starter template: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

- Documentation: https://docs.github.com/en/actions/guides/building-and-testing-nodejs
- Examples
  - https://github.com/bmaupin/devops-cheatsheets/commit/402e2c21b9ef36353e5257ea73ff16713bd5d0f4
  - https://github.com/bmaupin/covid19-trends/blob/master/.github/workflows/build.yml

Then see if we can get coveralls working (see here for latest version: https://github.com/coverallsapp/github-action)

```yaml
    - name: npm install, make test-coverage
      run: |
        npm install
        make test-coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
```
